#!/usr/bin/env bash
# initial setup of variables and includes

export phpvm_path

if [[ -z "${phpvm_path:-}" ]]
then
  phpvm_path="$HOME/.phpvm"
fi

export phpvm_temp_dir="$phpvm_path/tmp"
export phpvm_raw_dir="$phpvm_temp_dir/raw"
export phpvm_src_dir="$phpvm_temp_dir/src"
export phpvm_install_dir="$phpvm_path/phps"

# dirs and perms
mkdir -p "$phpvm_raw_dir"
mkdir -p "$phpvm_src_dir"
chmod +x $phpvm_path/scripts/*

. "$phpvm_path/functions/use_php"
. "$phpvm_path/functions/reload"

