#!/usr/bin/env bash
# initial setup of variables and includes

export phpvm_temp_dir="$phpvm_path/tmp"
export phpvm_raw_dir="$phpvm_temp_dir/raw"
export phpvm_src_dir="$phpvm_temp_dir/src"
export phpvm_install_dir="$phpvm_path/phps"

if [ -z "$phpvm_using" ]
then
  export phpvm_using=""
fi

# dirs and perms
mkdir -p "$phpvm_raw_dir"
mkdir -p "$phpvm_src_dir"
chmod +x $phpvm_path/scripts/*

. "$phpvm_path/scripts/functions/util"
. "$phpvm_path/scripts/functions/use_php"
. "$phpvm_path/scripts/functions/list"
. "$phpvm_path/scripts/functions/remove"
. "$phpvm_path/scripts/functions/reload"

