#!/usr/bin/env bash

__phpvm_list() {

  # Display a list of php versions available for use

  if [ -d "$phpvm_install_dir" ]
  then
    echo -e "\nInstalled Versions"
    echo -e "------------------"

    if [ -z "$phpvm_using" ]
    then
      ls "$phpvm_install_dir" | sed 's/php-/ /g'
    else
      # show starz!
      ls "$phpvm_install_dir" | sed 's/php-/ /g' | sed "s/$phpvm_using/\* $phpvm_using/g"
    fi

    echo ''
    echo '(* == active php version)'
  else
    echo "No phps installed"
  fi
}
