#!/usr/bin/env bash

__phpvm_unload() {

  # Unload the current php version from path

  if [ ! -z "$phpvm_using" ]
  then
    echo "Unloading $phpvm_using"
    # @ is the delimiter
    PATH=`echo $PATH | sed "s@:*$phpvm_path/phps/php-.*/bin@@g"`
    export PATH
    export phpvm_using=''
  fi
}

__phpvm_remove() {

  # Completely remove a version of php

  if [ -z "$1" ]
  then
    echo "No version specified"
    return 0
  fi

  # first arg is the php version
  phpvm_php_path="$phpvm_path/phps/php-$1"

  if [ -d "$phpvm_php_path" ]
  then

    # unload from path
    __phpvm_unload

    # confirm the choice
    read -p "Completely shred php-$1 (y/n)? " choice

    case "$choice" in
      y|Y )
        rm -rf "$phpvm_php_path"
        echo "Removed php-$1"
        return 0
        ;;
      n|N )
        echo "Not shredding"
        return 0
        ;;
      * ) echo
        "Invalid choice, not proceding"
        return 0
        ;;
    esac

    echo "Using $1"

  else
    echo "Version is not installed"
    __phpvm_list
  fi
}
