#!/usr/bin/env bash

__phpvm_use_php() {

  if [ -z "$1" ]
  then
    echo "No version specified"
    return 0
  fi

  # first arg is the php version
  phpvm_bin_path="$phpvm_path/phps/php-$1/bin"

  if [ -d "$phpvm_bin_path" ]
  then
    # @ is the delimiter
    PATH=`echo $PATH | sed "s@:*$phpvm_path/phps/php-.*/bin@@g"`

    # remove existing bin path
    PATH="$PATH:${phpvm_bin_path}"
    export PATH
    echo "Using $1"

  else
    echo "Version is not installed"
    __phpvm_list
  fi
}
