#!/usr/bin/env bash
# misc util functions

__phpvm_usage() {
  cat "$phpvm_path/scripts/text/usage.txt"
  echo ''
}

__phpvm_cleanup() {

  #  Clean up temp files

  rm -rf "$phpvm_temp_dir/"

  echo "Cleanup of $phpvm_temp_dir/ complete"
}
