#!/usr/bin/env bash
# misc util functions

__phpvm_usage() {
  cat "$phpvm_path/scripts/text/usage.txt"
  echo ''
}

__phpvm_available_versions()
{
  echo "Available versions"
  echo ""
  ls "$phpvm_install_dir" | grep "php-.*"
  echo ""
}

__phpvm_cleanup()
{
  rm -rf "$phpvm_temp_dir/"
}
