#!/usr/bin/env bash
# the main script to pass args to larger commands
set -o errexit

. "$phpvm_path/scripts/functions/util"

case "$1" in
  install)
    shift
    "$phpvm_path/scripts/install_php" "$@"
    ;;
  *)
    # catchall for usage
    __phpvm_usage
    ;;
esac


