#!/usr/bin/env bash
set -o errexit

. $phpvm_path/scripts/util


# TODO remove reload every time
reload_env

case "$1" in
  install)
    shift
    install_php "$@"
    ;;
  reload)
    reload_env
    ;;
  *)
    usage
    ;;
esac


