#!/usr/bin/env bash
# the main sourced file, calls from here should manage
# the shell env
# TODO organize better

export phpvm_path

if [[ -z "${phpvm_path:-}" ]]
then
  phpvm_path="$HOME/.phpvm"
fi

# initialize env vars, and include functions
. "$phpvm_path/functions/init"

# main function sourced into command line
function phpvm()
{

  # auto reload only for development
  case "$1" in
    reload)
      shift
      __phpvm_reload_env
      ;;
    *)
      if [ -f "$phpvm_path/.dev" ]
      then
        __phpvm_reload_env
      fi
      ;;
  esac

  case "$1" in
    use)
      shift
      __phpvm_use_php "$@"
      ;;
    *)
      "$phpvm_path/scripts/main" "$@"
      ;;
  esac
}
